version: '3.8'

services:
  web:
    container_name: myweb_app
    image: wangdg68/myweb:latest
    environment:
      - NODE_ENV=production
      - PORT=3999
      - MONGODB_URI=mongodb://stock:681123@192.168.1.2:27017/edu?authSource=admin
      - N8N_WEBHOOK_URL=https://n8n.wdg.us.kg/webhook
    ports:
      - '3999:3999'
    restart: unless-stopped
    volumes:
      - ./courses:/app/courses
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3999/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

